resources:
  - name: repo_vijay
    type: GitRepo
    configuration:
      gitProvider: vijay_github
      path: vijayreddy1991/jfrog
#       files:  # optional
#         include: pipelines.yml
#         exclude: readme
      branches:  # optional
        include: debain
#         exclude: git
#       tags:  # optional
#         include: 
#         exclude: 
#       buildOn:  # optional
#         commit: true
#          pullRequestCreate: true
#          pullRequestClose: false
#          releaseCreate: false
#          tagCreate: false
#       shallowDepth: 10  # optional 
      
pipelines:
  - name: jfrog_pipeline
    steps:
      - name: test1
        type: Bash
        configuration:
          affinityGroup: debain 
          priority: 0
          timeoutSeconds: 50000
#           nodePool: ubuntu_16
#           chronological: true
          environmentVariables:
            env1: value1
            env2: value2
          integrations:
            - name: aws_keys
#             - name: artifactoryIntegration  
          inputResources:
            - name: repo_vijay
          runtime:       
            type: image     #<image/host>
            image:
              custom:
                name: drydock/u16
                tag: master
#                 registry: art
#                 sourceRepository: docker # required if registry is artifactory
#                 region: <string> # required if registry is AWS
#                 options:
        execution:
          onExecute:
            - echo "test1"  
            - pwd
            - terraform --version
            - printenv
#             - echo $res_repo_vijay_resourcePath
#             - pushd $res_repo_vijay_resourcePath
            - pwd
            - sudo su
            - terraform init
            - pushd $res_repo_vijay_resourcePath
            - terraform init            
            - ls -la
#             - terraform plan -var-file="$PWD/keys.tfvar"
            - PWD=$(pwd)
            - echo PWD=$PWD
            - replace_envs $PWD/keys.tfvar
            - terraform apply -auto-approve -var-file="$PWD/keys.tfvar"
            - terraform output vijay_ip
            - vijay_ip_address=$(terraform output vijay_ip)
            - echo "$vijay_ip_address"
            - add_pipeline_variables vijay_ip_address=$vijay_ip_address
            - add_pipeline_files $PWD/terraform.tfstate jfrog_pipeline
            - popd
#             - pushd $res_repo_vijay_resourcePath
#             - chmod 777 provision.sh
#             - ./provision.sh
#             - popd

      - name: test2
        type: Bash
        configuration:
          affinityGroup: debain
          priority: 0
          timeoutSeconds: 50000
#           nodePool: ubuntu_16
          chronological: true
          environmentVariables:
            env1: value1
            env2: value2
          integrations:
            - name: bindu_pem 
            - name: ART_keys
          inputSteps:
            - name: test1
          inputResources:
            - name: repo_vijay            
          runtime:       
            type: image     #<image/host>
            image:
              custom:
                name: drydock/u16
                tag: master
        execution:
          onExecute:
            - echo "Test2"
            - printenv
            - pushd $res_repo_vijay_resourcePath
            - PWD=$(pwd)
            - echo $PWD
            - sudo apt-get update
            - echo "$int_bindu_pem_key" > bindu.pem
            - cat $PWD/bindu.pem
            - echo $vijay_ip_address
            - echo "$PWD"
            - sudo chmod 600 "$PWD"/bindu.pem
            - cp "$PWD"/bindu.pem ~/.ssh/
            - cat ~/.ssh/bindu.pem
            - which ssh
            - scp -i ~/.ssh/bindu.pem $PWD/pipeline_installer.sh ubuntu@$vijay_ip_address:~
            - ssh -i ~/.ssh/bindu.pem ubuntu@$vijay_ip_address ls
            - ssh -i ~/.ssh/bindu.pem ubuntu@$vijay_ip_address chmod 777 pipeline_installer.sh
            - ssh -i ~/.ssh/bindu.pem ubuntu@$vijay_ip_address ./pipeline_installer.sh
            

      - name: test3
        type: Bash
        configuration:
          affinityGroup: debain 
          priority: 0
          timeoutSeconds: 50000
# #           nodePool: ubuntu_16
#           chronological: true
          environmentVariables:
            env1: value1
            env2: value2
          integrations:
            - name: aws_keys
          inputSteps:
            - name: test2
          inputResources:
            - name: repo_vijay
          runtime:       
            type: image     #<image/host>
            image:
              custom:
                name: drydock/u16
                tag: master
        execution:
          onExecute:
            - echo "test3"  
            - pushd $res_repo_vijay_resourcePath
            - echo $PWD
            - echo "$vijay_ip_address"
            - terraform init
            - replace_envs $PWD/keys.tfvar
            - restore_pipeline_files jfrog_pipeline $PWD/terraform.tfstate
            - terraform destroy -auto-approve -var-file="$PWD/keys.tfvar"
            - popd

#       - name: test4
#         type: Bash
#         configuration:
#           affinityGroup: rpm
#           priority: 0
#           timeoutSeconds: 50000
# #           nodePool: ubuntu_16
#           chronological: true
#           environmentVariables:
#             env1: value1
#             env2: value2
# #           integrations:
# #             - name: dockerHubIntegration
# #             - name: artifactoryIntegration  
#           inputSteps:
#             - name: test3
# #           inputResources:
# #             - name: vijay_git
# #               trigger: true    # default true
# #           outputResources:
# #             - name: myOutputResource1  
#           runtime:       
#             type: image       #<image/host>
#             image:
#               auto:
#                 language: go
#                 versions:
#                   - 1.12.5
# # e
# #                 name: drydock/u16node
# #                 tag: master
# #                 registry: art
# #                 sourceRepository: docker # required if registry is artifactory
# #                 region: <string> # required if registry is AWS
# #                 options:
#         execution:
#           onExecute:
#             - echo "test4"  
#             - printenv
